# @package _global_

defaults:
  - _self_
  - data: null
  - model: null
  - trainer: default.yaml

hydra:
  searchpath:
    - file://config/
  sweep:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
