_target_: pytorch_lightning.Trainer

log_every_n_steps: 10
max_epochs: 100

logger:
  _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
