_target_: pytorch_lightning.Trainer

accelerator: cpu

log_every_n_steps: 10
max_epochs: 100

enable_progress_bar: False

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  entity: null
  project: vae-playland
  group: celeba
  save_dir: outputs
  settings:
    _target_: wandb.Settings
    start_method: thread

callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
