_target_: pytorch_lightning.Trainer

accelerator: cpu

max_epochs: 100

enable_progress_bar: False

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  entity: null
  project: vae-playland
  group: celeba
  save_dir: null

callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
